// Generated by CoffeeScript 1.6.3
(function() {
  var fuc;

  fuc = function() {
    var name, words;
    name = "rihanna  dont stop    music";
    words = name.replace(/\s+/g, "_");
    return alert(words);
  };

}).call(this);
