// Generated by CoffeeScript 1.6.3
(function() {
  chrome.browserAction.onClicked.addListener(function(tab) {
    return chrome.tabs.create({
      "url": 'index.html'
    });
  });

  chrome.runtime.onMessage.addListener(function(request, sender, sendResponse) {
    console.log(sender.tab ? "from a content script:" + sender.tab.url : "from the extension");
    chrome.tabs.create({
      "url": request.greeting
    });
    return sendResponse({
      farewell: "goodbye"
    });
  });

}).call(this);
