// Generated by CoffeeScript 1.6.3
(function() {
  var clickHandler, func, http_handle, reset_handle;

  func = function() {
    var cache, lastfm;
    console.log("APP");
    cache = new LastFMCache();
    lastfm = new LastFM({
      apiKey: 'e3d64479d574074eac7058d08de0dda7',
      apiSecret: '063d322566d3a8bcbd48ac160aa5097a',
      cache: cache
    });
    return lastfm.track.getSimilar({
      artist: $("#a_name").val(),
      track: $("#s_name").val(),
      limit: 5
    }, {
      success: function(data) {
        var song, _i, _len, _ref;
        _ref = data.similartracks.track;
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          song = _ref[_i];
          $('#sucks').append("<li><a>" + song.artist.name + " - " + song.name + "</a></li>");
        }
        $('#sucks').listview("refresh");
        $("#a_name").val("");
        return $("#s_name").val("");
      }
    }, {
      error: function(code, message) {}
    });
  };

  clickHandler = function() {
    return func();
  };

  reset_handle = function() {
    console.log("TEST");
    $('#sucks').remove();
    return $('#sucks').listview("refresh");
  };

  http_handle = function() {
    return $.ajax("http://www.mrtzcmp3.net/snow_patrol_chasing_cars_1s.html", {
      success: function(data, textStatus, jqXHR) {
        var dl_url, myvar;
        myvar = data.match(/D\?.*?_/)[0];
        dl_url = "http://www.mrtzcmp3.net/" + myvar.substr(2, 8) + "mrtzcmp3";
        $.ajax(dl_url, {
          success: function(data, textStatus, jqXHR) {
            return alert("DOWNLOAD");
          },
          error: function(jqXHR, textStatus, errorThrown) {
            return alert("DOWNLOAD FAILED");
          }
        });
        return console.log("HTTP REQUEST");
      },
      error: function(jqXHR, textStatus, errorThrown) {
        alert(textStatus + " FAILED HTTP " + errorThrown);
        return console.log("FAILED REQUEST");
      }
    });
  };

  $(function() {
    console.log("LOADED");
    $("#sub").click(func);
    $("#reset").click(reset_handle);
    return $("#test").click(http_handle);
  });

}).call(this);
