// Generated by CoffeeScript 1.6.3
(function() {
  var clickHandler, func;

  func = function() {
    var cache, lastfm;
    console.log("LOADED");
    cache = new LastFMCache();
    lastfm = new LastFM({
      apiKey: 'e3d64479d574074eac7058d08de0dda7',
      apiSecret: '063d322566d3a8bcbd48ac160aa5097a',
      cache: cache
    });
    return lastfm.track.getSimilar({
      artist: $("#a_name").val(),
      track: $("#s_name").val(),
      limit: 20
    }, {
      success: function(data) {
        var song, _i, _len, _ref;
        _ref = data.similartracks.track;
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          song = _ref[_i];
          $('#sucks').append("<li><a>" + song.artist.name + " - " + song.name + "</a></li>");
        }
        $('#sucks').listview("refresh");
        $("#a_name").val("");
        return $("#s_name").val("");
      }
    }, {
      error: function(code, message) {}
    });
  };

  clickHandler = function() {
    return func();
  };

  document.addEventListener('DOMContentLoaded', function() {
    return document.querySelector('button').addEventListener('click', clickHandler);
  });

}).call(this);
